CREATE TABLE IF NOT EXISTS schedule (
    id                  VARCHAR(36)     PRIMARY KEY,
    principal           DECIMAL(19, 2)  NOT NULL,
    annual_rate         DECIMAL(10, 2)  NOT NULL,
    installments        INT             NOT NULL,
    amortization_system VARCHAR(10)     NOT NULL,
    start_date          DATE            NOT NULL,
    total_interest      DECIMAL(19, 2)  NOT NULL,
    total_payment       DECIMAL(19, 2)  NOT NULL
);

CREATE TABLE IF NOT EXISTS installment (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id     VARCHAR(36)     NOT NULL REFERENCES schedule (id),
    number          INT             NOT NULL,
    due_date        DATE            NOT NULL,
    installment     DECIMAL(19, 2)  NOT NULL,
    principal       DECIMAL(19, 2)  NOT NULL,
    interest        DECIMAL(19, 2)  NOT NULL,
    balance         DECIMAL(19, 2)  NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_installment_schedule ON installment (schedule_id);
